# Generated by Django 5.1.7 on 2025-04-07 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpa_events', '0003_alter_user_groups_alter_user_user_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering position of the choice in the question'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordering position of the question in the survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this survey was created'),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this survey was last updated'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_answer',
            field=models.ForeignKey(blank=True, help_text='Selected choice for multiple-choice questions', null=True, on_delete=django.db.models.deletion.CASCADE, to='adpa_events.choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, to='adpa_events.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Answer for text-based questions', null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='Question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_choices', to='adpa_events.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(help_text='The choice text (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this event was created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Detailed description of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Date and time when event ends'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Location/venue of the event', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='User who organized this event', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Date and time when event starts'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Name of the event (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this event was last updated'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False, help_text='Whether the user attended the event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(help_text='Event being registered for', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_registrations', to='adpa_events.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When the registration was made'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(help_text='User who registered', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether a response to this question is required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('radio', 'Single Choice'), ('checkbox', 'Multiple Choice')], help_text='Type of question/response expected', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(help_text='Survey this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_questions', to='adpa_events.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='The question text (max 500 characters)', max_length=500),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='event',
            field=models.OneToOneField(blank=True, help_text='Event this survey is associated with (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adpa_survey', to='adpa_events.event'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the survey is currently accepting responses'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(help_text='Title of the survey', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when user account was created', verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's email address (used as username)", max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="User's first name", max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='adpa_user_groups', related_query_name='adpa_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False, help_text='Designates special membership status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="User's last name", max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='adpa_user_permissions', related_query_name='adpa_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this response was submitted')),
                ('survey', models.ForeignKey(help_text='Survey being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_responses', to='adpa_events.survey')),
                ('user', models.ForeignKey(help_text='User who submitted the response', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(help_text='Response this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='adpa_answers', to='adpa_events.surveyresponse'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
