# Generated by Django 5.1.7 on 2025-04-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('governance', 'Governance'), ('membership', 'Membership'), ('reports', 'Reports'), ('templates', 'Templates'), ('financial', 'Financial')], max_length=20)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.CharField(max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('file_url', models.URLField()),
                ('restricted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('workshop', 'Workshop'), ('deadline', 'Deadline'), ('conference', 'Conference')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('virtual_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Angola', 'Angola'), ('South Africa', 'South Africa'), ('Zimbabwe', 'Zimbabwe'), ('Namibia', 'Namibia'), ('Tanzania', 'Tanzania'), ('Ghana', 'Ghana'), ('Guinea', 'Guinea'), ('DRC', 'DR Congo'), ('Congo', 'Republic of Congo'), ('Togo', 'Togo'), ('Central African Republic', 'Central African Republic'), ('Cameroon', 'Cameroon'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Sierra Leone', 'Sierra Leone'), ('Liberia', 'Liberia'), ('Gabon', 'Gabon'), ('Algeria', 'Algeria'), ('Mali', 'Mali'), ('Mozambique', 'Mozambique'), ('Russia', 'Russia')], max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Observer', 'Observer')], max_length=15)),
                ('since', models.IntegerField()),
                ('tier', models.CharField(choices=[('Founding', 'Founding'), ('Full', 'Full'), ('Associate', 'Associate'), ('Observer', 'Observer')], max_length=15)),
                ('payment_status', models.CharField(choices=[('Current', 'Current'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Not Applicable', 'Not Applicable')], max_length=15)),
                ('representative', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('countries', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Planning', 'Planning'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], max_length=15)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('progress', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('implementing_agency', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
